# Generated by Django 5.2 on 2026-07-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_added_by'),
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjournal',
            name='favorite_quests',
            field=models.ManyToManyField(blank=True, related_name='favorited_in', to='games.quest'),
        ),
    ]
