# Generated by Django 5.2 on 2026-07-24 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('on_hold', 'On Hold')], max_length=11)),
                ('review', models.TextField(blank=True, null=True)),
                ('personal_rating', models.FloatField(blank=True, null=True)),
                ('is_on_showcase', models.BooleanField(default=False)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('favorite_quests', models.ManyToManyField(blank=True, related_name='favorited_in', to='catalog.quest')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal', to='catalog.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(upload_to='journal/screenshots')),
                ('caption', models.TextField(blank=True, null=True)),
                ('user_journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='journal.userjournal')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=250)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='catalog.character')),
                ('user_journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_quotes', to='journal.userjournal')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_comments', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='journal.userjournal')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='FavoriteCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_on_showcase', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='favorited_by_users', to='catalog.character')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='favorite_characters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('character', 'user'), name='users_favorite_characters')],
            },
        ),
        migrations.AddConstraint(
            model_name='userjournal',
            constraint=models.UniqueConstraint(fields=('game', 'user'), name='users_journal'),
        ),
    ]
