# Generated by Django 5.2 on 2026-07-24 07:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import catalog.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('realise_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1958), django.core.validators.MaxValueValidator(catalog.models.current_year)])),
                ('publisher', models.CharField(max_length=200)),
                ('cover_image', models.ImageField(upload_to='games/covers')),
                ('metacritic_rating', models.FloatField()),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_games', to=settings.AUTH_USER_MODEL)),
                ('genres', models.ManyToManyField(related_name='games', to='catalog.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='characters/photos/')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='catalog.game')),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quests', to='catalog.game')),
            ],
        ),
    ]
