# Generated by Django 5.2 on 2026-07-25 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_character_options_alter_game_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='realise_year',
            new_name='release_year',
        ),
    ]
