# Generated by Django 5.2 on 2026-07-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_metacritic_rating_game_metacritic_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='games/banners'),
        ),
    ]
