# Generated by Django 5.2 on 2026-07-21 11:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import games.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('slug', models.SlugField(help_text='Page identifier for the URL. Only Latin letters, numbers, hyphens, and underscores are allowed', unique=True)),
                ('realise_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1958), django.core.validators.MaxValueValidator(games.models.current_year)])),
                ('publisher', models.CharField(max_length=150)),
                ('cover_image', models.ImageField(upload_to='games/covers')),
                ('metacritic_rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='characters/photos/')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='games.game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(related_name='games', to='games.genre'),
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quests', to='games.game')),
            ],
        ),
    ]
