# Generated by Django 5.2 on 2026-07-25 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_realise_year_game_release_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='metacritic_rating',
            new_name='metacritic_score',
        ),
    ]
