# Generated by Django 5.2 on 2026-07-26 18:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_game_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='photo',
            field=models.ImageField(upload_to='catalog/characters/photos/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='banner_image',
            field=models.ImageField(blank=True, default='', upload_to='catalog/games/banners'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='cover_image',
            field=models.ImageField(upload_to='catalog/games/covers'),
        ),
        migrations.AlterField(
            model_name='game',
            name='metacritic_score',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
